#' Function for formatting UESI city names
#'
#' Use this function to format City names for plots within the UESI project
#' @param x A vector of citynames
#' @return Formatted city names ready for plotting
#' @export
format_city_name <- function(x) {
  x <- tolower(as.character(x))

  x[x == "addisababa"] <- "Addis Ababa"
  x[x == "albuquerque"] <- "Albuquerque"
  x[x == "alexandria"] <- "Alexandria"
  x[x == "alger"] <- "Algiers"
  x[x == "amsterdam"] <- "Amsterdam"
  x[x == "anchorage"] <- "Anchorage"
  x[x == "asuncion"] <- "Asuncion"
  x[x == "athens"] <- "Athens"
  x[x == "atlanta"] <- "Atlanta"
  x[x == "baltimore"] <- "Baltimore"
  x[x == "bamako"] <- "Bamako"
  x[x == "bangalore"] <- "Bengaluru"
  x[x == "bangkok"] <- "Bangkok"
  x[x == "barcelona"] <- "Barcelona"
  x[x == "beijing"] <- "Beijing"
  x[x == "berlin"] <- "Berlin"
  x[x == "billings"] <- "Billings"
  x[x == "bogota"] <- "Bogotá"
  x[x == "boston"] <- "Boston"
  x[x == "bratislava"] <- "Bratislava"
  x[x == "bridgeport"] <- "Bridgeport"
  x[x == "brisbane"] <- "Brisbane"
  x[x == "brussels"] <- "Brussels"
  x[x == "bucharest"] <- "Bucharest"
  x[x == "budapest"] <- "Budapest"
  x[x == "buenosaires"] <- "Buenos Aires"
  x[x == "cairns"] <- "Cairns"
  x[x == "caracas"] <- "Caracas"
  x[x == "casablanca"] <- "Casablanca"
  x[x == "charleston"] <- "Charleston"
  x[x == "charlotte"] <- "Charlotte"
  x[x == "chelyabinsk"] <- "Chelyabinsk"
  x[x == "chengdu"] <- "Chengdu"
  x[x == "chennai"] <- "Chennai"
  x[x == "chicago"] <- "Chicago"
  x[x == "chongqing"] <- "Chongqing"
  x[x == "ciudaddeguatemala"] <- "Guatemala City"
  x[x == "ciudaddepanama"] <- "Panama City"
  x[x == "cleveland"] <- "Cleveland"
  x[x == "coimbra"] <- "Coimbra"
  x[x == "colon"] <- "Colón"
  x[x == "conarky"] <- "Conakry"
  x[x == "copenhagen"] <- "Copenhagen"
  x[x == "dakar"] <- "Dakar"
  x[x == "dalian"] <- "Dalian"
  x[x == "darwin"] <- "Darwin"
  x[x == "delhi"] <- "New Delhi"
  x[x == "denver"] <- "Denver"
  x[x == "detroit"] <- "Detroit"
  x[x == "dodoma"] <- "Dodoma"
  x[x == "dublin"] <- "Dublin"
  x[x == "edinburgh"] <- "Edinburgh"
  x[x == "evansville"] <- "Evansville"
  x[x == "fargo"] <- "Fargo"
  x[x == "fortaleza"] <- "Fortaleza"
  x[x == "freetown"] <- "Freetown"
  x[x == "guangzhou"] <- "Guangzhou"
  x[x == "hamburg"] <- "Hamburg"
  x[x == "hangzhou"] <- "Hangzhou"
  x[x == "harare"] <- "Harare"
  x[x == "hobart"] <- "Hobart"
  x[x == "hochiminh"] <- "Ho Chi Minh City"
  x[x == "hongkong"] <- "Hong Kong"
  x[x == "honolulu"] <- "Honolulu"
  x[x == "houston"] <- "Houston"
  x[x == "istanbul"] <- "Istanbul"
  x[x == "jakarta"] <- "Jakarta"
  x[x == "johannesburg"] <- "Johannesburg"
  x[x == "kabul"] <- "Kabul"
  x[x == "kampala"] <- "Kampala"
  x[x == "kiev"] <- "Kyiv"
  x[x == "kigali"] <- "Kigali"
  x[x == "kinshasa"] <- "Kinshasa"
  x[x == "kolkata"] <- "Kolkata"
  x[x == "lagos"] <- "Lagos"
  x[x == "lasvegas"] <- "Las Vegas"
  x[x == "lemba"] <- "Kinshasa"
  x[x == "lima"] <- "Lima"
  x[x == "lisbon"] <- "Lisbon"
  x[x == "lome"] <- "Lome"
  x[x == "london"] <- "London"
  x[x == "losangeles"] <- "Los Angeles"
  x[x == "louisville"] <- "Louisville"
  x[x == "luanda"] <- "Luanda"
  x[x == "lyons"] <- "Lyon"
  x[x == "madrid"] <- "Madrid"
  x[x == "malaga"] <- "Málaga"
  x[x == "managua"] <- "Managua"
  x[x == "manaus"] <- "Manaus"
  x[x == "manila"] <- "Manila"
  x[x == "maputo"] <- "Maputo"
  x[x == "marseille"] <- "Marseille"
  x[x == "medellin"] <- "Medellin"
  x[x == "melbourne"] <- "Melbourne"
  x[x == "mexico"] <- "Mexico City"
  x[x == "mexicocity"] <- "Mexico City"
  x[x == "miami"] <- "Miami"
  x[x == "milan"] <- "Milan"
  x[x == "milwaukee"] <- "Milwaukee"
  x[x == "minneapolis"] <- "Minneapolis"
  x[x == "monrovia"] <- "Monrovia"
  x[x == "montevideo"] <- "Montevideo"
  x[x == "montreal"] <- "Montreal"
  x[x == "moscow"] <- "Moscow"
  x[x == "munich"] <- "Munich"
  x[x == "nairobi"] <- "Nairobi"
  x[x == "nanjing"] <- "Nanjing"
  x[x == "nashville"] <- "Nashville"
  x[x == "newyork"] <- "New York"
  x[x == "niamey"] <- "Niamey"
  x[x == "nizhny"] <- "Nizhny Novgorod"
  x[x == "nouakchott"] <- "Nouakchott"
  x[x == "novosibirsk"] <- "Novosibirsk"
  x[x == "omaha"] <- "Omaha"
  x[x == "oslo"] <- "Oslo"
  x[x == "ottawa"] <- "ottawa"
  x[x == "paris"] <- "Paris"
  x[x == "paterson"] <- "Paterson"
  x[x == "perth"] <- "Perth"
  x[x == "philadelphia"] <- "Philadelphia"
  x[x == "phnompenh"] <- "Phnom Penh"
  x[x == "phoenix"] <- "Phoenix"
  x[x == "portland"] <- "Portland"
  x[x == "porto"] <- "Porto"
  x[x == "qingdao"] <- "Qingdao"
  x[x == "quetzaltenango"] <- "Quetzaltenango"
  x[x == "quito"] <- "Quito"
  x[x == "reykjavik"] <- "Reykjavík"
  x[x == "riodejaneiro"] <- "Rio de Janeiro"
  x[x == "saintpetersburg"] <- "Saint Petersburg"
  x[x == "saltlakecity"] <- "Salt Lake City"
  x[x == "sanfrancisco"] <- "San Francisco"
  x[x == "sanjose"] <- "San Jose"
  x[x == "sansalvador"] <- "San Salvador"
  x[x == "santiago"] <- "Santiago"
  x[x == "santodomingo"] <- "Santo Domingo"
  x[x == "saopaulo"] <- "São Paulo"
  x[x == "seattle"] <- "Seattle"
  x[x == "seoul"] <- "Seoul"
  x[x == "seville"] <- "Seville"
  x[x == "shanghai"] <- "Shanghai"
  x[x == "shenzhen"] <- "Shenzhen"
  x[x == "singapore"] <- "Singapore"
  x[x == "siouxfalls"] <- "Sioux Falls"
  x[x == "stlouis"] <- "St. Louis"
  x[x == "stockholm"] <- "Stockholm"
  x[x == "sydney"] <- "Sydney"
  x[x == "tegucigalpa"] <- "Tegucigalpa"
  x[x == "tehran"] <- "Tehran"
  x[x == "telaviv"] <- "Tel Aviv"
  x[x == "tianjin"] <- "Tianjin"
  x[x == "tokyo"] <- "Tokyo"
  x[x == "toowoomba"] <- "Toowoomba"
  x[x == "toronto"] <- "Toronto"
  x[x == "tulsa"] <- "Tulsa"
  x[x == "tunis"] <- "Tunis"
  x[x == "valencia"] <- "Valencia"
  x[x == "vancouver"] <- "Vancouver"
  x[x == "vienna"] <- "Vienna"
  x[x == "vientiane"] <- "Vientiane"
  x[x == "warsaw"] <- "Warsaw"
  x[x == "wellington"] <- "Wellington"
  x[x == "wichita"] <- "Wichita"
  x[x == "wuhan"] <- "Wuhan"
  x[x == "yamoussoukro"] <- "Yamoussoukro"
  x[x == "yangon"] <- "Yangon"
  x[x == "yaounde"] <- "Yaounde"
  x[x == "zagreb"] <- "Zagreb"
  x[x == "zhenjiang"] <- "Zhenjiang"
  x[x == "zurich"] <- "Zürich"


  return(x)
}

